# Generated by Django 5.0.6 on 2024-07-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='data_envio',
            field=models.DateTimeField(),
        ),
    ]
